version: '3'

services:
  agile-health:
    build: ./agile-health
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dconfig.file=/workspace/application.properties", "-jar", "agile-health.jar"]
    volumes:
      - './src/main/resources/application.properties:/workspace/application.properties'
    restart: always
    container_name: agile-health
    ports:
      - "8080:8080"
    environment:
      - PG_DATASOURCE_URL=jdbc:postgresql://db:5432/agilehealth
      - PG_NAME=pgadmin
      - PG_PASS=pgadmin
    tty: true
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=agilehealth
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  postgres_data: